import { NextPage } from "Next";
import Head from "Next/head";

import styles from "../../styles/Home.module.css";

interface HeaderProps {
  title: string;
}

const Header: NextPage<HeaderProps> = ({ title }: HeaderProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header>
          <nav>Her kommer navigering</nav>
        </header>
      </div>
    </>
  );
};

export default Header;
