import { NextPage } from "next";
import Head from "next/head";

import Navbar from "./Navbar.component";

interface HeaderProps {
  title: string;
}

const Header: NextPage<HeaderProps> = ({ title }: HeaderProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
};

export default Header;
