import type { NextPage } from "next";
import Head from "next/head";

const CVContent: NextPage = () => {
  return (
    <>
      <Head>
        <title>DFWeb v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Velkommen til CV</h1>
      </main>
    </>
  );
};

export default CVContent;
