import Head from "next/head";

import Navbar from "./Navbar.component";

interface IHeaderProps {
  title: string;
}

const Header = ({ title }: IHeaderProps): JSX.Element => (
  <>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
  </>
);

export default Header;
