import type { NextPage } from "next";
import Head from "next/head";

import IndexContent from "../components/Index/IndexContent.component";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DFWeb v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexContent />
    </div>
  );
};

export default Home;
