name: Codecov upload

on: [pull_request]

jobs:
  codecov:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust this to your project's Node.js version

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests with coverage
        run: npm run test

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
